name: test

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - run: go mod download
      - run: go generate ./...
      - run: go test ./...
      - run: bash build.sh
